### PR TITLE
Added tests for tables

### PR DESCRIPTION
**Pull request by shibasisp**
Added tests for `tables`.

### CODE REVIEW

**Comment by shibasisp** [comment]
I haven't touched `test_images.py`, yet it's showing error for that one. I can't figure out the reason.
And the 2nd error for `msutil`, I have changed in my another PR.

**Comment by tammojan** [comment]
> And the 2nd error for msutil, I have changed in my another PR.

Could you help a bit and give the number of that PR?

**Comment by shibasisp** [comment]
Apology for submitting the PR late. Now, I have submitted the PR and it's #98 .

**Comment by tammojan** [comment]
The tests here fail due to use of `has_key`, which you have fixed in #98. So we should merge #98 first to get a green test result here.

**Comment by tammojan** [comment]
The tests fail on the issue that was fixed in #98, so that should be fixed when merging to master.

@shibasisp , do you know why coverage decreased? You've added many new tests, so I'd say the coverage should increase.

**Pull request closed without merging**
