### PR TITLE
Add dependency on casacore libs

### LINKED ISSUE #25: setup.py doesn't detect changes in casacore
The interface of one of the functions in libcasa_casa had changed (from 'casa::ArrayBase::baseReform(casa::ArrayBase&, casa::IPosition const&) const' to 
'casa::ArrayBase::baseReform(casa::ArrayBase&, casa::IPosition const&, bool) const'), but setup.py did not force a recompile of the sources using this changed file; it bluntly copied the so-files from the cache ('build/lib.linux-x86_64-2.7') into the install directory. As a result I got the following error when trying to import a pyrap module:

$ python -c 'import pyrap.tables'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "pyrap/tables.py", line 1, in <module>
    from casacore.tables import *
  File "casacore/tables/__init__.py", line 60, in <module>
    from table import table
  File "casacore/tables/table.py", line 44, in <module>
    from _tables import Table
ImportError: casacore/tables/_tables.so: undefined symbol: _ZNK4casa9ArrayBase10baseReformERS0_RKNS_9IPositionE

The workaround is to ditch the build directory every time, but that's a bit of a pity, because most of the time a recompile is not needed.

### PR DESCRIPTION
**Pull request by tammojan**
This should fix #25 in most cases, by adding the library files to the dependencies. Finding the full path is actually done by the compiler. I tried to mimic the search path, but can't guarantee that always works. If the libraries are not found, the dependency is not added and the old behavior is kept (so no error is thrown).

### CODE REVIEW

**Comment by alxames** [comment]
tammojan asked me to review/test:
I can confirm that it works: rebuilding and installing an updated version of casacore (all /usr/local/lib/libcasa_* changed) will not trigger a rebuild with the current version of setup.py (casacore-python is unchanged), but it will with this patch.

Looking at the patch, it makes sense, sort of. What I'd like to see is:
* the default behavior the other way around: always rebuild unless dependency checking indicates work can be saved. Then, the warning print could indicate that this may trigger a complete rebuild of the bindings; now users won't know what this message implies.
* What if only e.g. libcasa_measures.so changed? You only check for casa_casa. Not suggesting that we do partial rebuilds (we don't support parallel builds either), just rule out any chance of incorrectly not rebuilding.
* Why do we have to guess lib dirs like that? How does casacore-python know where casacore is installed (i.e. which libdir to add to -L to link to)? Somehow, it must know it. Can't we use that info directly? Enough people put casacore under /opt.

( Random thought: Could it be that 99% of casacore-python reinstalls come down to a rebuild anyway? If so, what about dropping the complexity and always issue a full rebuild? )

**Comment by tammojan** [comment]
@alxames , thanks for the detailed review.
About your comments:

- I don't know how to force a rebuild from the source. Ffom the command-line you can add `--force` which forces a rebuild.
- The check for `casa_casa` is only to see if the libraries can be found at all. Then the dependencies are all added appropriately (tables depends on casa_tables, casa_meas, casa_casa, etc.).
- We have to 'guess' the lib dirs because they are resolved by the c++ linker, not python. We can add a path to the lib search path (by giving `build_ext --library-dirs`), but resolving the full system path is harder. If the libs are in `/opt`, you would give them to `--library-dirs` and the current python logic would find them.

I don't think we should force a rebuild always. I agree that 99.9% of the time when you invoke setup.py manually, you want a rebuild, but setup.py is also called by package manager.

**Comment by gijzelaerr** [comment]
this code is python2 only and not python3 compatible:

```
λ  .virtualenv3/bin/python setup.py
  File "setup.py", line 107
    print "Warning: could not find casa library dir for dependency tracking"
                                                                           ^
SyntaxError: Missing parentheses in call to 'print'
```

**Comment by tammojan** [comment]
Updated code as per @gijzelaerr's comment, add brackets in print statements. Not tested on python3, but should work.

**Comment by tammojan** [comment]
Update the doc as per @alxames suggestion. @gijzelaerr , could you have a look and / or just merge this?

**Pull request merged**
