### PR TITLE
Expose MeasurementSet object

### PR DESCRIPTION
**Pull request by sjperkins**
Expose the MeasurementSet object, as well as the requiredTableDesc static method.

### CODE REVIEW

**Comment by sjperkins** [comment]
This is still a WIP. I've created the PR as I'd like input from the maintainers on how to interface with casacore.

**Comment by gervandiepen** [comment]
This is a non-trivial change and our time is quite limited.
I guess the requiredTableDesc and creating the MS are the most important
functions. Access to the tables and columns can easily be done through
pyrap.tables, although it does not offer support for the TableMeasures
interface.

**Comment by sjperkins** [comment]
> This is a non-trivial change and our time is quite limited

Understood

>I guess the requiredTableDesc and creating the MS are the most important functions. Access to the tables and columns can easily be done through pyrap.tables, although it does not offer support for the TableMeasures interface.

I'm playing with how to exposing `TableDesc` and `ColumnDesc` via a `Record` to the user. As you say this is works out to a fairly extensive change. Also, while I've created a separate `ms` module I've realised its probably better to fold everything into the `tables` module.

Perhaps the simplest would be to add drop the changes and add some sort of default table creator factory that could then be added to the the boost::python `Table` class? For e.g. the following pseudo-code:

```cpp
TableProxy create_default_table(String name)
{
  TableDesc td = MeasurementSet::requiredTableDesc();
  return TableProxy(td);
}
```

and then

```cpp
  class_<TableProxy>("Table")
   ...
   .def("default_table", &create_default_table, (args("name")))
   .staticmethod("default_table")
```

**Comment by sjperkins** [comment]
On hold for a while since I think this will need https://github.com/casacore/casacore/pull/559 to do a proper job of it.

**Pull request closed without merging**
