### PR TITLE
Added tests for casacore.images

### PR DESCRIPTION
**Pull request by shibasisp**

### CODE REVIEW

**Comment by tammojan** [comment]
Great, thanks!

**Comment by shibasisp** [comment]
@tammojan I don't understand why the @coveralls says the coverage decreased. Do you know why?

**Comment by tammojan** [comment]
I don't understand. It's complaining about tables.py . Can you see the coveralls output?

**Comment by shibasisp** [comment]
Yes. But I havent touched tables.py still its complaining.

**Pull request merged**
