### PR TITLE
Quanta: add dicts with all units and prefixes with Python 2.6 tests

### PR DESCRIPTION
**Pull request by gijzelaerr**
fix for this PR

https://github.com/casacore/python-casacore/pull/39

### CODE REVIEW

**Comment by tammojan** [comment]
I cancelled the travis push trigger, will wait for the PR triggered build to finish before merging.

**Comment by tammojan** [comment]
Tests failed:
```
ERROR: Failure: ImportError (No module named unittest2)
```

Apparently the setup.py line does not do what you expect..

**Comment by gijzelaerr** [comment]
yeah I saw. Ill have a look.

2016-02-26 15:27 GMT+02:00 Tammo Jan Dijkema <notifications@github.com>:

> Tests failed:
>
> ERROR: Failure: ImportError (No module named unittest2)
>
> Apparently the setup.py line does not do what you expect..
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/casacore/python-casacore/pull/46#issuecomment-189271775>
> .
>



-- 
Gijs Molenaar
http://pythonic.nl

**Comment by tammojan** [comment]
@gijzelaerr Is this good to go now?

**Pull request merged**
