### PR TITLE
Use setuptools scm

### PR DESCRIPTION
**Pull request by gmloose**
Use `setuptools_scm` to automate versioning. This avoids the risk of forgetting to manually update the version information, e.g., when creating a new release.

### CODE REVIEW

**Review by tammojan — APPROVED** [review]
Looks good to me! (Although I'm not a fan of merging in the master and prefer rebasing, but it's ok with me to overlook that now.)

**Comment by gmloose** [comment]
I'm happy to rebase it on the current master, but probably need to force push then.

**Comment by aroffringa** [comment]
> I'm happy to rebase it on the current master, but probably need to force push then.

Not sure for casacore, but for the other repos that's what we basically always do.

**Comment by gmloose** [comment]
Rebased to master. May need another review. Since @tammojan is away for a few weeks, maybe @aroffringa can have a look instead.

**Review by tammojan — APPROVED** [review]

**Pull request merged**
