### PR TITLE
Added gaussian2d test

### PR DESCRIPTION
**Pull request by shibasisp**
Issue #6

### CODE REVIEW

**Comment by tammojan** [comment]
Thanks for adding a test. Apparently, the test fails when using Casacore 2.0. Can you see the travis output? In case you cannot, here it is:
```
======================================================================

ERROR: test_gaussian2d_dtype (test_funcionals.TestFunctionals)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/casacore/python-casacore/tests/test_funcionals.py", line 69, in test_gaussian2d_dtype

    self.test_gaussian2d(1)

  File "/home/travis/build/casacore/python-casacore/tests/test_funcionals.py", line 60, in test_gaussian2d

    gauss2d.set_masks([True, True, False, True, True, True])

  File "/home/travis/build/casacore/python-casacore/casacore/functionals/functional.py", line 166, in set_masks

    _functional._setmasks(self, msk)

RuntimeError: RecordRep::get_pointer - incorrect data type used for field params

======================================================================

FAIL: test_gaussian2d (test_funcionals.TestFunctionals)

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/casacore/python-casacore/tests/test_funcionals.py", line 62, in test_gaussian2d

    gauss2d.get_masks() == [True, True, False, True, True, True])

AssertionError: False is not true

----------------------------------------------------------------------

Ran 11 tests in 0.527s
```

**Comment by shibasisp** [comment]
I am not getting any error when tested locally.

**Comment by gijzelaerr** [comment]
@tammojan this raises an interesting issue, do we want to support all casacores or only the latest one? We can make decision where we say development of python-casacore only happens for the latest casacore and if you have an older casacore you need an older python-casacore. Lets move the discussion to the gitter channel.

**Comment by tammojan** [comment]
I thinks supporting only the latest casacore version is fine, however we need to test this during installation. See #79.

**Comment by gervandiepen** [comment]
The fix in FunctionalProxy::setmasks (PR #327, 11-Mar-2016) was not available in casacore-2.0 yet, so therefore it fails for the version. It tried to get a complex value from a Record as a double.

**Comment by tammojan** [comment]
@shibasisp Could you rebase this onto the master? Since we now require casacore 2.3.0, travis shouldn't fail anymore. However, we've got ourselves a merge conflict..

**Pull request merged**
